version: '3'
services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - sonarnet
  scanner:
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ./packages:/usr/src
    networks:
      - sonarnet
networks:
  sonarnet:
