name: Run Nx Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run affected packages
        run: npx nx affected --target=build --parallel=3
